package Executables;

import java.io.File;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Unmarshaller;

import autoGenerated.Europe;
import autoGenerated.Europe.Pays;

public class Main_TP3 {

	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub

		JAXBContext jc = JAXBContext.newInstance(Europe.class);
		Unmarshaller unmarshaller = jc.createUnmarshaller();
		Europe racine = (Europe) unmarshaller.unmarshal(
				new File("C:\\Users\\Exost\\Documents\\workspace-spring-tool-suite-4-4.6.2.RELEASE\\TP1 XML\\TP1.xml"));
		List<Pays> listePaysEurope = racine.getPays();
		for (Pays p : listePaysEurope) {
			System.out.println("Nom Pays : " + p.getNomPays());
			System.out.println("Date Relevé : " + p.getDateDeReleve());
			System.out.println("Données Démographiques : ");
			System.out.println("Population : " + p.getDonneesDemographiques().getPopulation().getValue());
			System.out.println("Taux Fecondite : " + p.getDonneesDemographiques().getTxFecondite().getValue());
			System.out.println("Données Economiques : ");
			System.out.println("Pib par habitant : " + p.getDonneesEconomiques().getPibParHabitant().getValue());
			System.out.println("Monnaie : " + p.getDonneesEconomiques().getMonnaie());
			System.out.println();
		}

	}

}
