package Executables;

import java.io.File;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;

import autoGenerated.Europe;
import autoGenerated.Europe.Pays;

public class Main_TP5 {

	public static void main(String[] args) throws JAXBException {
		// TODO Auto-generated method stub

		// Lecture et mise en mémoire du fichier OG
		JAXBContext jc = JAXBContext.newInstance(Europe.class);
		Unmarshaller unmarshaller = jc.createUnmarshaller();
		Europe racine = (Europe) unmarshaller.unmarshal(new File(
				"C:\\Users\\Exost\\Documents\\workspace-spring-tool-suite-4-4.6.2.RELEASE\\tp_xml\\src\\main\\resources\\TP1.xml"));
		List<Pays> listePaysEurope = racine.getPays();

		// Ecriture dans le nouveau XML
		JAXBContext jc2 = JAXBContext.newInstance(Europe.class);
		Marshaller marshaller = jc.createMarshaller();
		marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);

		// Ecriture du XML lu (Racine from TP1) dans le fichier test TP5.xml
		File os = new File(
				"C:\\Users\\Exost\\Documents\\workspace-spring-tool-suite-4-4.6.2.RELEASE\\tp_xml\\src\\main\\resources\\testEcritureTP5.xml");
		marshaller.marshal(racine, os);
	}

}
