//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.15 at 11:19:45 AM CET 
//


package autoGenerated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pays" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="nomPays" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="dateDeReleve"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="donneesDemographiques"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="population"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
 *                                     &lt;attribute name="unite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="txFecondite"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
 *                                     &lt;attribute name="infoTx" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="donneesEconomiques"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="pibParHabitant"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="unite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="monnaie" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pays"
})
@XmlRootElement(name = "europe")
public class Europe {

    @XmlElement(required = true)
    protected List<Europe.Pays> pays;

    /**
     * Gets the value of the pays property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pays property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPays().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Europe.Pays }
     * 
     * 
     */
    public List<Europe.Pays> getPays() {
        if (pays == null) {
            pays = new ArrayList<Europe.Pays>();
        }
        return this.pays;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="nomPays" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="dateDeReleve"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                 &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="donneesDemographiques"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="population"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
     *                           &lt;attribute name="unite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="txFecondite"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
     *                           &lt;attribute name="infoTx" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="donneesEconomiques"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="pibParHabitant"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="unite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="monnaie" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nomPays",
        "dateDeReleve",
        "donneesDemographiques",
        "donneesEconomiques"
    })
    public static class Pays {

        @XmlElement(required = true)
        protected String nomPays;
        @XmlElement(required = true)
        protected Europe.Pays.DateDeReleve dateDeReleve;
        @XmlElement(required = true)
        protected Europe.Pays.DonneesDemographiques donneesDemographiques;
        @XmlElement(required = true)
        protected Europe.Pays.DonneesEconomiques donneesEconomiques;

        /**
         * Gets the value of the nomPays property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNomPays() {
            return nomPays;
        }

        /**
         * Sets the value of the nomPays property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNomPays(String value) {
            this.nomPays = value;
        }

        /**
         * Gets the value of the dateDeReleve property.
         * 
         * @return
         *     possible object is
         *     {@link Europe.Pays.DateDeReleve }
         *     
         */
        public Europe.Pays.DateDeReleve getDateDeReleve() {
            return dateDeReleve;
        }

        /**
         * Sets the value of the dateDeReleve property.
         * 
         * @param value
         *     allowed object is
         *     {@link Europe.Pays.DateDeReleve }
         *     
         */
        public void setDateDeReleve(Europe.Pays.DateDeReleve value) {
            this.dateDeReleve = value;
        }

        /**
         * Gets the value of the donneesDemographiques property.
         * 
         * @return
         *     possible object is
         *     {@link Europe.Pays.DonneesDemographiques }
         *     
         */
        public Europe.Pays.DonneesDemographiques getDonneesDemographiques() {
            return donneesDemographiques;
        }

        /**
         * Sets the value of the donneesDemographiques property.
         * 
         * @param value
         *     allowed object is
         *     {@link Europe.Pays.DonneesDemographiques }
         *     
         */
        public void setDonneesDemographiques(Europe.Pays.DonneesDemographiques value) {
            this.donneesDemographiques = value;
        }

        /**
         * Gets the value of the donneesEconomiques property.
         * 
         * @return
         *     possible object is
         *     {@link Europe.Pays.DonneesEconomiques }
         *     
         */
        public Europe.Pays.DonneesEconomiques getDonneesEconomiques() {
            return donneesEconomiques;
        }

        /**
         * Sets the value of the donneesEconomiques property.
         * 
         * @param value
         *     allowed object is
         *     {@link Europe.Pays.DonneesEconomiques }
         *     
         */
        public void setDonneesEconomiques(Europe.Pays.DonneesEconomiques value) {
            this.donneesEconomiques = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class DateDeReleve {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "format")
            protected String format;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the format property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormat() {
                return format;
            }

            /**
             * Sets the value of the format property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormat(String value) {
                this.format = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="population"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
         *                 &lt;attribute name="unite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="txFecondite"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
         *                 &lt;attribute name="infoTx" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "population",
            "txFecondite"
        })
        public static class DonneesDemographiques {

            @XmlElement(required = true)
            protected Europe.Pays.DonneesDemographiques.Population population;
            @XmlElement(required = true)
            protected Europe.Pays.DonneesDemographiques.TxFecondite txFecondite;

            /**
             * Gets the value of the population property.
             * 
             * @return
             *     possible object is
             *     {@link Europe.Pays.DonneesDemographiques.Population }
             *     
             */
            public Europe.Pays.DonneesDemographiques.Population getPopulation() {
                return population;
            }

            /**
             * Sets the value of the population property.
             * 
             * @param value
             *     allowed object is
             *     {@link Europe.Pays.DonneesDemographiques.Population }
             *     
             */
            public void setPopulation(Europe.Pays.DonneesDemographiques.Population value) {
                this.population = value;
            }

            /**
             * Gets the value of the txFecondite property.
             * 
             * @return
             *     possible object is
             *     {@link Europe.Pays.DonneesDemographiques.TxFecondite }
             *     
             */
            public Europe.Pays.DonneesDemographiques.TxFecondite getTxFecondite() {
                return txFecondite;
            }

            /**
             * Sets the value of the txFecondite property.
             * 
             * @param value
             *     allowed object is
             *     {@link Europe.Pays.DonneesDemographiques.TxFecondite }
             *     
             */
            public void setTxFecondite(Europe.Pays.DonneesDemographiques.TxFecondite value) {
                this.txFecondite = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
             *       &lt;attribute name="unite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Population {

                @XmlValue
                protected double value;
                @XmlAttribute(name = "unite")
                protected String unite;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public double getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(double value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the unite property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUnite() {
                    return unite;
                }

                /**
                 * Sets the value of the unite property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUnite(String value) {
                    this.unite = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;double"&gt;
             *       &lt;attribute name="infoTx" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class TxFecondite {

                @XmlValue
                protected double value;
                @XmlAttribute(name = "infoTx")
                protected String infoTx;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public double getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(double value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the infoTx property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInfoTx() {
                    return infoTx;
                }

                /**
                 * Sets the value of the infoTx property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInfoTx(String value) {
                    this.infoTx = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="pibParHabitant"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="unite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="monnaie" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pibParHabitant",
            "monnaie"
        })
        public static class DonneesEconomiques {

            @XmlElement(required = true)
            protected Europe.Pays.DonneesEconomiques.PibParHabitant pibParHabitant;
            @XmlElement(required = true)
            protected String monnaie;

            /**
             * Gets the value of the pibParHabitant property.
             * 
             * @return
             *     possible object is
             *     {@link Europe.Pays.DonneesEconomiques.PibParHabitant }
             *     
             */
            public Europe.Pays.DonneesEconomiques.PibParHabitant getPibParHabitant() {
                return pibParHabitant;
            }

            /**
             * Sets the value of the pibParHabitant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Europe.Pays.DonneesEconomiques.PibParHabitant }
             *     
             */
            public void setPibParHabitant(Europe.Pays.DonneesEconomiques.PibParHabitant value) {
                this.pibParHabitant = value;
            }

            /**
             * Gets the value of the monnaie property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMonnaie() {
                return monnaie;
            }

            /**
             * Sets the value of the monnaie property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMonnaie(String value) {
                this.monnaie = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="unite" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class PibParHabitant {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "unite")
                protected String unite;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the unite property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUnite() {
                    return unite;
                }

                /**
                 * Sets the value of the unite property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUnite(String value) {
                    this.unite = value;
                }

            }

        }

    }

}
